export const GET_STATE = "GET_STATE";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const CHANGE_COLORS = "CHANGE_COLORS";
export const ALWAYS = "ALWAYS";
export const SET_ACTIVE_BUTTON = "SET_ACTIVE_BUTTON";
export const UPDATE_CHOSEN_COLOR = "UPDATE_CHOSEN_COLOR";
export const CHANGE_LIGHTNESS = "CHANGE_LIGHTNESS";
export const RESET = "RESET";